### ISSUE TITLE
Broken macros in tools.cmake

### ISSUE THREAD

**Issue by rlalik** [StableCoder/cmake-scripts#22]
The macro `clang_tidy` uses `${ARGN}` variable whereas remaining `include_what_you_use` and `cppcheck` stil relay on `xxx_STRING` which honestly I don't know where it comes from. I've checked doc of cmake back to 3.0 and there is no mentioning of `xxx_STRING`. Where does it come from?

Please fix lines 32 and 40 in `tools.cmake`.

**Comment by StableCoder** [comment]
Fixed in [6c11e34](https://github.com/StableCoder/cmake-scripts/commit/6c11e34cae48205cad84f4e433083c0579e7fa6b), thanks for the heads up.
