### ISSUE TITLE
`ccov-all*` not compatible on Windows

### ISSUE THREAD

**Issue by mscofield0** [StableCoder/cmake-scripts#25]
Hey again, just thought I'd open this so there's an active issue to refer to in regards to this.

> Unfortunately, the ccov-all* targets are still non-functional on Windows, and I'm still trying to figure out a solution.

from [here](https://github.com/StableCoder/cmake-scripts/issues/24#issuecomment-828878026)

**Comment by StableCoder** [comment]
These issues should be fixed now, as of [aa8c42](https://github.com/StableCoder/cmake-scripts/commit/aa8c42bf67beee5568472f6db4676c0e9399c4ff).

**Comment by mscofield0** [comment]
Yep, works here, closing it.
