### ISSUE TITLE
Exclusions do not work for ccov-all-* targets

### ISSUE THREAD

**Issue by ambroff** [StableCoder/cmake-scripts#3]
First of all, thanks for publishing this work. The code coverage library in this repo saved me a lot of trouble.

I have a large project with many, many test executables. These test executables cover code for many static library targets. Some of these static library targets have many test executables.

Then the main build artifact is an executable that links with all of these static libraries.

So the way I structured this using your library was to:

```
include(code-coverage)
add_code_coverage_all_targets()
```

And then for every library and test executable, `target_code_coverage(target AUTO ALL EXCLUDE ${test_cpp_files})` is invoked.

This works fine for the report target of each of those separate library or test executable targets, but it doesn't work for the `ccov-all*` targets, since those exclusions aren't propagated to top-level targets.

I have a really gross patch to fix this in my project, but I thought that I'd call this out here.

https://gist.github.com/ambroff/64e9e9cc7ac1000366c05e5ed59cca95

This patch works fine for my use case but I don't think it's general enough, since I'm using this to generate a giant regular expression that matches any of the test source files provided.

**Comment by sergeyklay** [comment]
@ambroff I ran into a similar problem, especially considering the fact that I wanted to achieve the same report for Linux (lcov) and macOS (llvm-cov). This declaration at the very top level did the trick:

```cmake
# Handle codecoverage
if(CODE_COVERAGE)
    # Now we can exclude the stuff that we aren't interested in from the tracefile:
    # 1) system deps; 2) tests; 3) build; 4) thridparty-code
    set(coverage_excludes EXCLUDE
        "/usr/*" "build/*" "*/build/*" "tests/*" "*/tests/*" "external/*" "*/external/*")
    add_code_coverage_all_targets(${coverage_excludes})
endif()
```

Then for every target I want code coverage I declare something like this:
```cmake
# Add definition for foobar library.
add_library(foobar STATIC
    foobar.cpp
    another.cpp)

# ...

if(CODE_COVERAGE)
    target_code_coverage(foobar AUTO ALL)
endif()
```

N.B. To declare exclusion you have use [globbing](http://www.tldp.org/LDP/abs/html/globbingref.html), _not regular expressions_.

**Comment by sergeyklay** [comment]
I think this one can be  closed due to the lack of any reaction.
