### ISSUE TITLE
Cross-compilation support

### ISSUE THREAD

**Issue by Blumentopf99** [StableCoder/cmake-scripts#42]
Currently the added `ccov` targets execute the built target with optional parameters. Unfortunately, that doesn't work when the binary is cross-compiled for a different architecture (like arm). In that case the binary has to be executed by an emulator like qemu, e.g. `/usr/bin/qemu-aarch64-static -L /usr/aarch64-linux-gnu -E LD_LIBRARY_PATH=/some/path ./test-binary`

Is there a way to add support for cross-compiled targets, perhaps by adding an additional optional parameter to provide an emulator?

If that's not possible then alternatively it would be nice to have an option to to suppress the generation of the `ccov` targets in order to avoid having non-functional targets.

**Comment by Blumentopf99** [comment]
Thanks a lot for your quick support! Meanwhile, I discovered a simpler solution. CMake has a feature for exactly that problem using the variable [CMAKE_CROSSCOMPILING_EMULATOR](https://cmake.org/cmake/help/latest/variable/CMAKE_CROSSCOMPILING_EMULATOR.html) when [CMAKE_CROSSCOMPILING](https://cmake.org/cmake/help/latest/variable/CMAKE_CROSSCOMPILING.html) is turned ON. We set `CMAKE_CROSSCOMPILING_EMULATOR` already and everything works fine when I patch `code-coverage.cmake` to:
```
add_custom_target(
  ccov-capture-${target_code_coverage_COVERAGE_TARGET_NAME}
  COMMAND ${CMAKE_COMMAND} -E rm -f ${COVERAGE_INFO}
  COMMAND ${LCOV_PATH} --directory ${CMAKE_BINARY_DIR} --zerocounters
  COMMAND ${CMAKE_CROSSCOMPILING_EMULATOR} $<TARGET_FILE:${TARGET_NAME}> ${target_code_coverage_ARGS}
  COMMAND
    ${LCOV_PATH} --directory ${CMAKE_BINARY_DIR} --base-directory
    ${CMAKE_SOURCE_DIR} --capture ${EXTERNAL_OPTION} --output-file
    ${COVERAGE_INFO}
  COMMAND ${EXCLUDE_COMMAND}
  DEPENDS ${TARGET_NAME})
```
If somebody doesn't use cross-compilation then `CMAKE_CROSSCOMPILING` is turned OFF. That should be considered somehow.

**Comment by StableCoder** [comment]
Nice.

I've added `${CMAKE_CROSSCOMPILING_EMULATOR}` to e4e0c48361d367e01e77e5efec8b778fa06bae2c, so it's now
```
COMMAND ${CMAKE_CROSSCOMPILING_EMULATOR}
                      ${target_code_coverage_PRE_ARGS} 
                      $<TARGET_FILE:${TARGET_NAME}> 
                      ${target_code_coverage_ARGS}
```

Luckily, if no cross-compiling is specified, the `CMAKE_CROSSCOMPILING_EMULATOR` is just empty.

**Comment by Blumentopf99** [comment]
Thanks, that works like a charm! 
```
COMMAND ${target_code_coverage_PRE_ARGS} 
                      ${CMAKE_CROSSCOMPILING_EMULATOR}
                      $<TARGET_FILE:${TARGET_NAME}> 
                      ${target_code_coverage_ARGS}
```
