### ISSUE TITLE
Support for C in tools.cmake

### ISSUE THREAD

**Issue by cconverse711** [StableCoder/cmake-scripts#46]
All the tools in `tools.cmake` are currently applied to only C++ code, however they all support C code as well. Supporting C should just be a fairly straightforward -- for example setting the `CMAKE_C_CLANG_TIDY` to match `CMAKE_CXX_CLANG_TIDY`

**Comment by StableCoder** [comment]
I committed c1a621af7f7b768257d8995215ef651b90702634, which I think covers it. let me know if there's still an issue.

**Comment by cconverse711** [comment]
Thank you, that looks good.

Though I am curious about the intended behavior of the cppcheck logic in `tools.cmake`. There's a `if (CPPECHECK)` check (note the typo) [here](https://github.com/StableCoder/cmake-scripts/commit/c1a621af7f7b768257d8995215ef651b90702634#diff-69d08d1c038fe2c5c57e4aa2ac33a2e169aa6586924cf0e220f6560fa17c435cL99) that will evaluate to false due to the typo, however the logic inside that check's body is modifying the `CMAKE_CXX_CPPCHECK` variable with additional cppcheck flags. But when the `cppcheck()` macro is invoked, the  `CMAKE_CXX_CPPCHECK` is overwritten and wipes out the cppcheck flags that were applied earlier. Are those flags supposed to persist, or is that an old approach for applying cppcheck flags that's no longer meant to be used?

**Comment by StableCoder** [comment]
Honestly, I'm not entirely sure anymore. Much of the implementation is several years old.

However, as you do note it was a bit confusing, so I've gone ahead and re-worked the implementation (ba834211257ad67a2373dd11be05a6418839e1bc), and hopefully made things much clearer.

I've gone fully down the road of giving better control of the tools to the calling scripts, and the ability to overwrite/clear flags at-will throughout.

Let me know if what it is now is still unclear, or what parts of it are, and I'll try to fix/make things even clearer.
