### ISSUE TITLE
Main page readme reports functionalities not available in latest release

### ISSUE THREAD

**Issue by Jazzinghen** [StableCoder/cmake-scripts#47]
I am using `cmake-scripts` through [CPM](https://github.com/cpm-cmake/CPM.cmake/), which accepts only tags (or semantic versioning tags, `v.X.Y.Z`) to specify which version of the project to retrieve.
I wanted to use `tools.cmake` in my project and use both `cppcheck` and `cppcheck_reset` as shown in the readme, however the reset function is not available in the last tag (i.e. `23.06`).

**Comment by StableCoder** [comment]
New tag/release [here](https://github.com/StableCoder/cmake-scripts/releases/tag/23.09) should resolve it.
